#!/bin/sh

sh -e

FILE=$1
URL=$2

#touch "$FILE.etag"
curl --compressed --silent --show-error --fail --write-out '%{http_code}: %{size_download} bytes downloaded\n' --etag-compare "$FILE.etag" --etag-save "$FILE.etag" --output "$FILE" "$URL"
#mv "$FILE.etag.tmp" "$FILE.etag"
